Fix casing for some file paths
When deploying to Netlify, builds are failing with these messages:

Error: icon (./src/images/GrpLogosmall.png) does not exist as defined in gatsb  y-config.js. Make sure the file exists relative to the root of the site.

Can't resolve './GrpLogo.png' in '/opt/build/repo/src/components/NavBar'
Can't resolve './UKaidlogo.png' in '/opt/build/repo/src/components/Footer'

When building locally, things are working well. This is most likely
because our local filesystems are case-insensitive where as Netlify's
build machines are case-sensitive.